//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int ID { get; set; }
        public int code { get; set; }
        public int userid { get; set; }
        public System.DateTime created_ate { get; set; }
        public Nullable<System.DateTime> exportdate { get; set; }
        public string deliveryaddress { get; set; }
        public string deliveryname { get; set; }
        public string deliveryphone { get; set; }
        public string deliveryemail { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public int status { get; set; }
    }
}
