//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID { get; set; }
        public int catid { get; set; }
        public int Submenu { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string img { get; set; }
        public string detail { get; set; }
        public int number { get; set; }
        public double price { get; set; }
        public double pricesale { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public int updated_by { get; set; }
        public int status { get; set; }
        public Nullable<int> sold { get; set; }
    }
}
