//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int ID { get; set; }
        public int parentId { get; set; }
        public string accessName { get; set; }
        public string description { get; set; }
        public string GropID { get; set; }
    }
}
